query WalletNFTs($address: String!, $first: Int, $after: String) {
    wallet(address: $address) {
        __typename
        ensName
        address
        tokens(first: $first, after: $after) {
            __typename
            pageInfo {
                __typename
                hasNextPage
                endCursor
            }
            edges {
                __typename
                node {
                    __typename
                    tokenId
                    images {
                        __typename
                        url
                    }
                    ... on ERC721Token {
                        contract {
                            __typename
                            address
                            ... on ERC721Contract {
                                __typename
                                symbol
                                name
                            }
                        }
                    }
                }
            }
        }
    }
}