query NFTDetails($contractAddress: String!, $tokenId: String!) {
    token(contractAddress: $contractAddress, tokenId: $tokenId) {
        __typename
        ... on ERC721Token {
            tokenId
            attributes {
                name
                value
            }
            contract {
                __typename
                address
                isVerified
                tokenStandard
                ... on ERC721Contract {
                    name
                }
            }
            images {
                height
                mimeType
                url
                width
            }
            name
            symbol
            metadata {
                animation_url
                background_color
                description
                external_url
                image
                image_data
                name
                youtube_url
            }
        }
    }
}