root: true
env:
  es6: true
  node: true
  mocha: true
extends:
  - eslint:recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - prettier
ignorePatterns:
  - .github
  - dist
  - node_modules
rules:
  "prettier/prettier": "error"
